# Generated by Django 3.0.14 on 2022-02-12 00:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=60)),
                ('email', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=9)),
                ('country_code', models.TextField(max_length=3)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='max_guest',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('num', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('is_bookable', models.BooleanField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotelbooking.Hotel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotelbooking.RoomType')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('localizador', models.IntegerField(primary_key=True, serialize=False)),
                ('num_guest', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('checkin_date', models.DateTimeField()),
                ('checkout_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotelbooking.Customer')),
                ('room_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotelbooking.Room')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotelbooking.RoomType')),
            ],
        ),
    ]
